language: elixir
otp_release:
  - 17.4
before_install:
 - cp config/config.exs.ci config/config.exs
env:
  - TEST_SUITE="mix coveralls.travis"
  - TEST_SUITE="mix bench test/*_test.exs"
  - NATIVE=1 TEST_SUITE="mix coveralls.travis"
  - NATIVE=1 TEST_SUITE="mix bench test/*_test.exs"
script: mix compile && $TEST_SUITE